### ISSUE TITLE
 failed to get `hdk3` as a dependency of package `dna_help v0.1.0

### ISSUE THREAD

**Issue by harlantwood** [h-be/acorn-hc#106]
I cloned the repo and ran `nix-shell`, which took a while but then gave me a shell.  I quit that and tried the first command in the readme with the following results:

```
$ nix-shell --run acorn-package

    Updating git repository `https://github.com/holochain/holochain.git`
  Installing holochain v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
    Updating git repository `https://github.com/holochain/lmdb-rs.git`
    Updating git repository `https://github.com/holochain/rkv.git`
    Updating crates.io index
   Compiling holochain_wasm_test_utils v0.0.1 (/Users/harlan/code/acorn-hc/.cargo/git/checkouts/holochain-391184137afba57c/4714fbd/crates/test_utils/wasm)
   Compiling holochain v0.0.1 (/Users/harlan/code/acorn-hc/.cargo/git/checkouts/holochain-391184137afba57c/4714fbd/crates/holochain)
    Finished release [optimized] target(s) in 15.29s
   Replacing /Users/harlan/code/acorn-hc/.cargo/bin/holochain
    Replaced package `holochain v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` with `holochain v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` (executable `holochain`)
    Updating git repository `https://github.com/holochain/holochain.git`
  Installing dna_util v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
    Updating git repository `https://github.com/holochain/lmdb-rs.git`
    Updating git repository `https://github.com/holochain/rkv.git`
    Updating crates.io index
warning: Patch `lmdb-rkv v0.14.0 (https://github.com/holochain/lmdb-rs.git#46043614)` was not used in the crate graph.
Patch `rkv v0.10.4 (https://github.com/holochain/rkv.git#6f6b4b5a)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
    Finished release [optimized] target(s) in 3.08s
   Replacing /Users/harlan/code/acorn-hc/.cargo/bin/dna-util
    Replaced package `dna_util v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` with `dna_util v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` (executable `dna-util`)
npm WARN acorn-tests@0.4.0 No description
npm WARN acorn-tests@0.4.0 No repository field.

audited 176 packages in 1.103s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
audited 26 packages in 0.633s
found 0 vulnerabilities

+ cargo build --release --target wasm32-unknown-unknown
    Updating git repository `ssh://git@github.com/holochain/holochain.git`
error: failed to get `hdk3` as a dependency of package `dna_help v0.1.0 (/Users/harlan/code/acorn-hc/crates/dna_help)`

Caused by:
  failed to load source for dependency `hdk3`

Caused by:
  Unable to update ssh://git@github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd

Caused by:
  failed to clone into: /Users/harlan/code/acorn-hc/.cargo/git/db/holochain-8605acaca5aa8bc8

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  no authentication available
```

**Comment by harlantwood** [comment]
I solved this by adding: `~/.cargo/config` configuration that looks like:

> ```toml
> [net]
> git-fetch-with-cli = true
> ```
> 
> which will instruct Cargo to fetch git repositories with the `git` CLI rather than with libgit2. Using this will read `.ssh/config` because that's what `git` does.

-- from https://github.com/rust-lang/cargo/issues/2078#issuecomment-434388584

Feel free to close if you like.

**Comment by harlantwood** [comment]
next issue:

```
 nix-shell --run acorn-package

    Updating git repository `https://github.com/holochain/holochain.git`
  Installing holochain v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
    Updating git repository `https://github.com/holochain/lmdb-rs.git`
    Updating git repository `https://github.com/holochain/rkv.git`
    Updating crates.io index
    Finished release [optimized] target(s) in 5.49s
   Replacing /Users/harlan/code/acorn-hc/.cargo/bin/holochain
    Replaced package `holochain v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` with `holochain v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` (executable `holochain`)
    Updating git repository `https://github.com/holochain/holochain.git`
  Installing dna_util v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
    Updating git repository `https://github.com/holochain/lmdb-rs.git`
    Updating git repository `https://github.com/holochain/rkv.git`
    Updating crates.io index
warning: Patch `lmdb-rkv v0.14.0 (https://github.com/holochain/lmdb-rs.git#46043614)` was not used in the crate graph.
Patch `rkv v0.10.4 (https://github.com/holochain/rkv.git#6f6b4b5a)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
    Finished release [optimized] target(s) in 2.59s
   Replacing /Users/harlan/code/acorn-hc/.cargo/bin/dna-util
    Replaced package `dna_util v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` with `dna_util v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` (executable `dna-util`)
npm WARN acorn-tests@0.4.0 No description
npm WARN acorn-tests@0.4.0 No repository field.

audited 176 packages in 1.336s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
audited 26 packages in 0.6s
found 0 vulnerabilities

+ cargo build --release --target wasm32-unknown-unknown
    Updating git repository `ssh://git@github.com/holochain/holochain.git`
  Downloaded serde_json v1.0.58
  Downloaded syn v1.0.42
  Downloaded paste v1.0.1
  Downloaded libc v0.2.78
  Downloaded 4 crates (865.1 KB) in 1.38s
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.42
   Compiling autocfg v1.0.1
   Compiling serde v1.0.104
   Compiling byteorder v1.3.4
   Compiling getrandom v0.1.15
   Compiling ryu v1.0.5
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling serde_json v1.0.58
   Compiling syn v0.15.44
   Compiling proc-macro-hack v0.5.18
   Compiling libc v0.2.78
   Compiling unicode-segmentation v1.6.0
   Compiling hashbrown v0.9.1
   Compiling cfg-if v0.1.10
   Compiling itoa v0.4.6
   Compiling ppv-lite86 v0.2.9
   Compiling constant_time_eq v0.1.5
   Compiling strum v0.18.0
   Compiling arrayref v0.3.6
   Compiling arrayvec v0.5.1
   Compiling base64 v0.12.3
   Compiling subtle v2.3.0
   Compiling paste v1.0.1
   Compiling num-traits v0.2.12
   Compiling indexmap v1.6.0
   Compiling blake2b_simd v0.5.10
   Compiling heck v0.3.1
   Compiling rand_core v0.5.1
   Compiling rand_chacha v0.2.2
   Compiling quote v1.0.7
   Compiling quote v0.6.13
   Compiling rand v0.7.3
   Compiling rmp v0.8.9
   Compiling holochain_serialized_bytes_derive v0.0.45
   Compiling serde_derive v1.0.104
   Compiling thiserror-impl v1.0.20
   Compiling paste-impl v0.1.12
   Compiling strum_macros v0.18.0
   Compiling derive_more v0.99.11
   Compiling paste v0.1.12
   Compiling thiserror v1.0.20
   Compiling serde-transcode v1.1.0
   Compiling rmp-serde v0.14.4
   Compiling serde_bytes v0.11.5
   Compiling holochain_serialized_bytes v0.0.45
   Compiling fixt v0.0.1 (ssh://git@github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
   Compiling holochain_wasmer_common v0.0.46
   Compiling holo_hash v0.0.1 (ssh://git@github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
   Compiling holochain_wasmer_guest v0.0.46
   Compiling holochain_zome_types v0.0.1 (ssh://git@github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
   Compiling hdk3_derive v0.0.1 (ssh://git@github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
   Compiling hdk3 v0.0.1 (ssh://git@github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
   Compiling dna_help v0.1.0 (/Users/harlan/code/acorn-hc/crates/dna_help)
   Compiling acorn_projects v0.4.0 (/Users/harlan/code/acorn-hc/dnas/projects/zomes/acorn_projects)
   Compiling acorn_profiles v0.4.0 (/Users/harlan/code/acorn-hc/dnas/profiles/zomes/acorn_profiles)
    Finished release [optimized] target(s) in 1m 37s
+ cd dnas/profiles
+ dna-util -c profiles.dna.workdir
+ cd ../..
+ cd dnas/projects
+ dna-util -c projects.dna.workdir
 21:24:12  dragon-184  ~  code  acorn-hc   master  %   nix-shell --run acorn-hc
    Updating git repository `https://github.com/holochain/holochain.git`
  Installing holochain v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
    Updating git repository `https://github.com/holochain/lmdb-rs.git`
    Updating git repository `https://github.com/holochain/rkv.git`
    Updating crates.io index
    Finished release [optimized] target(s) in 3.93s
   Replacing /Users/harlan/code/acorn-hc/.cargo/bin/holochain
    Replaced package `holochain v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` with `holochain v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` (executable `holochain`)
    Updating git repository `https://github.com/holochain/holochain.git`
  Installing dna_util v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)
    Updating git repository `https://github.com/holochain/lmdb-rs.git`
    Updating git repository `https://github.com/holochain/rkv.git`
    Updating crates.io index
warning: Patch `lmdb-rkv v0.14.0 (https://github.com/holochain/lmdb-rs.git#46043614)` was not used in the crate graph.
Patch `rkv v0.10.4 (https://github.com/holochain/rkv.git#6f6b4b5a)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
    Finished release [optimized] target(s) in 2.52s
   Replacing /Users/harlan/code/acorn-hc/.cargo/bin/dna-util
    Replaced package `dna_util v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` with `dna_util v0.0.1 (https://github.com/holochain/holochain.git?rev=4714fbddc48f1f9987c9f574b8d06510ea58ab16#4714fbdd)` (executable `dna-util`)
npm WARN acorn-tests@0.4.0 No description
npm WARN acorn-tests@0.4.0 No repository field.

audited 176 packages in 1.147s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
audited 26 packages in 0.639s
found 0 vulnerabilities

+ acorn-package
+ cargo build --release --target wasm32-unknown-unknown
    Finished release [optimized] target(s) in 0.07s
+ cd dnas/profiles
+ dna-util -c profiles.dna.workdir
+ cd ../..
+ cd dnas/projects
+ dna-util -c projects.dna.workdir
+ npm run start

> acorn-hc@0.4.0 start /Users/harlan/code/acorn-hc
> npx @holochain-open-dev/holochain-run-dna dnas/profiles/profiles.dna.gz

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn lair-keystore ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lair-keystore',
  path: 'lair-keystore',
  spawnargs: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! acorn-hc@0.4.0 start: `npx @holochain-open-dev/holochain-run-dna dnas/profiles/profiles.dna.gz`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the acorn-hc@0.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/harlan/.npm/_logs/2020-10-24T07_27_18_160Z-debug.log
```

**Comment by harlantwood** [comment]
This was apparently because holochain had not been initialized on my machine.

I did:

```
nix-shell
holochain -i
```

And hit enter a few times to install DB, keystore, etc, and then the above command seems to work.

**Comment by harlantwood** [comment]
All good now!  Running both client and server successfully.  👍
